#!/usr/bin/env python3
"""gen_chipset_long_tests.py — auto-generate longword-write-split tests
for every adjacent-pair chipset register.

Why this exists: K1.3 ROM code uses MOVE.L to chipset addresses to set
two adjacent 16-bit registers in ONE instruction.  Examples:

  MOVE.L #-1, $DFF044       ; sets BLTAFWM and BLTALWM
  MOVE.L D0, $DFF064        ; sets BLTAMOD and BLTDMOD
  MOVE.L A0, $DFF020        ; sets DSKPTH and DSKPTL
  MOVE.L A0, $DFF080        ; sets COP1LCH and COP1LCL

Each pair needs explicit longword-split handling in `rtl/m68k_bus.v`
(canonical Amiga translator).  When it's MISSING, the chipset adapter
drops the low 16 bits silently, leaving the second register stale.
We've shipped fixes for this bug THREE times now: BLTAFWM/ALWM (t152),
BLT*PT shadows (canon path), BLTAMOD/CMOD splits (t156, this session).

This tool emits an .s test for every adjacent pair that:
  1. pre-seeds both halves with sentinels
  2. issues MOVE.L with a known split-pattern value
  3. reads both halves back, asserting they hold the correct halves

If any pair regresses (or a future pair is added without long handling),
the generated test fails immediately at make-test time.

Usage:
    python3 tools/gen_chipset_long_tests.py --out tests/gen/

Each pair emits `tests/gen/tg_<pair_name>_long.s`.  The Makefile's
auto-discovery `wildcard tests/*.s` won't pick these up — add them
manually OR adjust the wildcard to include `tests/gen/*.s`.
"""
import argparse
import os
import sys


# (label, hi_addr, hi_name, lo_addr, lo_name, readable, notes)
# Adjacent 16-bit pairs that CAN be hit by MOVE.L to the hi address.
# `readable=True` if the chipset exposes a CPU-side read path; otherwise
# we use a write-then-trigger-side-effect verification instead of read.
PAIRS = [
    # ── Blitter masks/mods (all readable) ──
    ("blt_afwm_alwm",  0xDFF044, "BLTAFWM", 0xDFF046, "BLTALWM", True,
     "K1.3 trackdisk: MOVE.L #-1, $DFF044 (t152 covers this; sanity check)"),
    ("blt_cmod_bmod",  0xDFF060, "BLTCMOD", 0xDFF062, "BLTBMOD", True,
     "Graphics.library .L to $DFF060 — second adjacent-pair landed 2026-06-03"),
    ("blt_amod_dmod",  0xDFF064, "BLTAMOD", 0xDFF066, "BLTDMOD", True,
     "Graphics.library .L to $DFF064 — root cause of WB1.3 boot wall (t156)"),
    # ── 32-bit DMA pointers (high+low halves; readable via own shadow) ──
    ("dskpt",          0xDFF020, "DSKPTH",  0xDFF022, "DSKPTL",  False,
     "Disk DMA pointer — trackdisk sets both halves via MOVE.L"),
    ("cop1lc",         0xDFF080, "COP1LCH", 0xDFF082, "COP1LCL", False,
     "Copper list 1 pointer — Intuition sets via MOVE.L A0,$DFF080"),
    ("cop2lc",         0xDFF084, "COP2LCH", 0xDFF086, "COP2LCL", False,
     "Copper list 2 pointer"),
    # ── Bitplane pointers (6 planes) ──
    ("bpl1pt",         0xDFF0E0, "BPL1PTH", 0xDFF0E2, "BPL1PTL", False,
     "Bitplane 1 — set every frame by Copper but K1.3 may seed via MOVE.L"),
    ("bpl2pt",         0xDFF0E4, "BPL2PTH", 0xDFF0E6, "BPL2PTL", False, ""),
    ("bpl3pt",         0xDFF0E8, "BPL3PTH", 0xDFF0EA, "BPL3PTL", False, ""),
    ("bpl4pt",         0xDFF0EC, "BPL4PTH", 0xDFF0EE, "BPL4PTL", False, ""),
    ("bpl5pt",         0xDFF0F0, "BPL5PTH", 0xDFF0F2, "BPL5PTL", False, ""),
    ("bpl6pt",         0xDFF0F4, "BPL6PTH", 0xDFF0F6, "BPL6PTL", False, ""),
    # ── Audio location pointers (4 channels) ──
    ("aud0lc",         0xDFF0A0, "AUD0LCH", 0xDFF0A2, "AUD0LCL", False, ""),
    ("aud1lc",         0xDFF0B0, "AUD1LCH", 0xDFF0B2, "AUD1LCL", False, ""),
    ("aud2lc",         0xDFF0C0, "AUD2LCH", 0xDFF0C2, "AUD2LCL", False, ""),
    ("aud3lc",         0xDFF0D0, "AUD3LCH", 0xDFF0D2, "AUD3LCL", False, ""),
    # ── Sprite pointers (8 sprites) ──
    ("spr0pt",         0xDFF120, "SPR0PTH", 0xDFF122, "SPR0PTL", False, ""),
    ("spr1pt",         0xDFF124, "SPR1PTH", 0xDFF126, "SPR1PTL", False, ""),
    ("spr2pt",         0xDFF128, "SPR2PTH", 0xDFF12A, "SPR2PTL", False, ""),
    ("spr3pt",         0xDFF12C, "SPR3PTH", 0xDFF12E, "SPR3PTL", False, ""),
    ("spr4pt",         0xDFF130, "SPR4PTH", 0xDFF132, "SPR4PTL", False, ""),
    ("spr5pt",         0xDFF134, "SPR5PTH", 0xDFF136, "SPR5PTL", False, ""),
    ("spr6pt",         0xDFF138, "SPR6PTH", 0xDFF13A, "SPR6PTL", False, ""),
    ("spr7pt",         0xDFF13C, "SPR7PTH", 0xDFF13E, "SPR7PTL", False, ""),
]


TEMPLATE_READABLE = """; AUTO-GENERATED by tools/gen_chipset_long_tests.py — DO NOT EDIT
; Verifies MOVE.L to {hi_name} (${hi:04X}) commits BOTH halves:
;   {hi_name} <- high16
;   {lo_name} (${lo:04X}) <- low16
;
; {notes}

        .org $400
start:
        move.l  #$00DFF000, A0

        ; Pre-seed with sentinels
        move.w  #$1234, ${hi_off:02X}(A0)         ; {hi_name} = $1234
        move.w  #$5678, ${lo_off:02X}(A0)         ; {lo_name} = $5678

        ; Read-back verify seed
        move.w  ${hi_off:02X}(A0), D2
        andi.l  #$0000FFFF, D2
        cmpi.l  #$00001234, D2
        bne     fail_seed_hi
        move.w  ${lo_off:02X}(A0), D2
        andi.l  #$0000FFFF, D2
        cmpi.l  #$00005678, D2
        bne     fail_seed_lo

        ; The test: MOVE.L #$DEADBEEF, ${hi_off:02X}(A0)
        ; Expected: {hi_name} <- $DEAD, {lo_name} <- $BEEF
        move.l  #$DEADBEEF, ${hi_off:02X}(A0)

        ; Verify both halves
        move.w  ${hi_off:02X}(A0), D2
        andi.l  #$0000FFFF, D2
        cmpi.l  #$0000DEAD, D2
        bne     fail_hi_after_long
        move.w  ${lo_off:02X}(A0), D2
        andi.l  #$0000FFFF, D2
        cmpi.l  #$0000BEEF, D2
        bne     fail_lo_after_long    ; <-- the bug class lives here

        stop    #0

fail_seed_hi:        stop   #1
fail_seed_lo:        stop   #2
fail_hi_after_long:  stop   #3
fail_lo_after_long:  stop   #4
"""


# For write-only registers (DSKPT, BPLnPT etc.), we can't read them back
# directly through the chipset slave.  We emit a smoke-test that just
# exercises the path; verifying it would land both halves needs a runtime
# probe on the internal shadow.  Useful as a coverage placeholder.
TEMPLATE_WRITE_ONLY = """; AUTO-GENERATED by tools/gen_chipset_long_tests.py — DO NOT EDIT
; Smoke-test MOVE.L to {hi_name} (${hi:04X}) — covers the longword-split
; bug class, but {hi_name}/{lo_name} are write-only chipset regs so a
; full readback verification needs a probe.  This test just exercises
; the path; failures from broken longword handling would manifest as
; downstream chipset state errors (e.g., disk DMA from wrong address)
; rather than a direct stop-code mismatch.
;
; {notes}

        .org $400
start:
        move.l  #$00DFF000, A0
        ; Pre-seed both halves with sentinels via 16-bit writes
        move.w  #$1234, ${hi_off:02X}(A0)
        move.w  #$5678, ${lo_off:02X}(A0)
        ; Longword that should split as $DEAD->{hi_name}, $BEEF->{lo_name}
        move.l  #$DEADBEEF, ${hi_off:02X}(A0)
        stop    #0
"""


def emit_test(out_dir, pair):
    label, hi, hi_name, lo, lo_name, readable, notes = pair
    hi_off = hi & 0xFF
    lo_off = lo & 0xFF
    name = f"tg_{label}_long"
    template = TEMPLATE_READABLE if readable else TEMPLATE_WRITE_ONLY
    body = template.format(
        hi=hi, hi_name=hi_name, hi_off=hi_off,
        lo=lo, lo_name=lo_name, lo_off=lo_off,
        notes=notes or "(no notes)")
    path = os.path.join(out_dir, f"{name}.s")
    with open(path, "w") as f:
        f.write(body)
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="tests/gen",
                    help="output directory for generated tests")
    ap.add_argument("--list", action="store_true",
                    help="list pairs and exit (no file output)")
    args = ap.parse_args()

    if args.list:
        for p in PAIRS:
            label, hi, hi_name, lo, lo_name, readable, notes = p
            tag = "R" if readable else "W"
            print(f"  [{tag}] {hi_name:8s} ${hi:04X} + {lo_name:8s} ${lo:04X}  {notes}")
        print(f"\nTotal: {len(PAIRS)} adjacent pairs")
        return

    os.makedirs(args.out, exist_ok=True)
    paths = [emit_test(args.out, p) for p in PAIRS]
    print(f"Generated {len(paths)} tests in {args.out}/:")
    for p in paths:
        print(f"  {p}")
    print()
    print("To run: add `tests/gen/*.s` to the wildcard in Makefile's TESTS,")
    print("OR cherry-pick the readable ones (R) — those have direct read")
    print("verification and will fail loudly if the bug class regresses.")


if __name__ == "__main__":
    main()
